### ISSUE TITLE
Pls help to produce the sonobuoy-plugin-systemd-logs for arm64

### ISSUE THREAD

**Issue by kevinzs2048** [heptio/sonobuoy-plugin-systemd-logs#4]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Deploy Sonobuoy on arm64 server failed due to this image gcr.io/heptio-images/sonobuoy-plugin-systemd-logs:latest don't have arm64 image

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
If OK, I can help to produce one but Could not upload to gci.io due to authorization.

**Environment:**
Arm64 , ubuntu bionic
- Sonobuoy version: (use `sonobuoy version`):
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version: kubeadm 1.15
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by johnSchnake** [comment]
#5 Addressed this; at this time we just haven't pushed new images but that is pending. Will close once that has been done.

**Comment by lubinsz** [comment]
@johnSchnake 
Hi,
When will the arm64 image be uploaded?
Thanks.

**Comment by johnSchnake** [comment]
Thanks for the ping; will post here once images have been pushed.

**Comment by johnSchnake** [comment]
Posted now and tagged with v0.2 and latest; Sonobuoy will choose the new images by default in all the platforms.

**Comment by kevinzs2048** [comment]
Great! Thanks for your help!
